USE [DataWarehouse]
GO

/****** Объект:  StoredProcedure [silver].[usp_LoadSilverOperativeTables]    Дата создания скрипта: 06.06.2026 14:43:01 ******/ 
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE OR ALTER PROCEDURE [gold].[usp_LoadGoldOperativeTables]
    AS
    BEGIN
        SET NOCOUNT ON;

        DECLARE @sql NVARCHAR(MAX);

SET @sql = N'
    INSERT INTO [gold].[oper_cm_moneyflow_kz]
    (
        [LOCATION],[STORE],[POS_NUMBER],[SHIFT_NUMBER],[SHIFT_PART],[DATE],[EUR LOAN],[EUR SALES]
      ,[EUR REFUND],[EUR PICKUP],[USD LOAN],[USD SALES],[USD REFUND],[USD PICKUP]
      ,[KZT LOAN],[KZT SALES],[KZT REFUND],[KZT PICKUP],[RUB LOAN],[RUB SALES],[RUB REFUND],[RUB PICKUP]
      ,[CNY LOAN],[CNY SALES],[CNY REFUND],[CNY PICKUP]
      ,[CARDS SALES],[CARDS REFUND],[OFFLINE CARD SALES],[OFFLINE CARD REFUND]
    )
SELECT
    SL.Location AS Location,
    SL.StoreName AS Store,
    CM.CASHCODE,
    CM.SHIFT,
    CASE 
        WHEN CAST(CM.TIME AS TIME) BETWEEN ''00:00:01'' AND ''08:00:00'' THEN N''Утро с 00:00:01 до 08:00:00''
        WHEN CAST(CM.TIME AS TIME) BETWEEN ''08:00:01'' AND ''20:00:00'' THEN N''День с 08:00:01 до 20:00:00''
        ELSE N''Вечер с 20:00:01 до 00:00:00''
    END AS ShiftPart,
    CAST(CM.DATE AS DATE) AS SaleDate,
    SUM(CASE WHEN CM.OPCODE = 80 AND CM.VALCODE = 3 THEN CM.VSUM ELSE 0 END) AS [EUR_Loan],        
    SUM(CASE WHEN CM.OPCODE = 72 AND CM.VALCODE = 3 THEN CM.VSUM ELSE 0 END) AS [EUR_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 3 THEN CM.VSUM ELSE 0 END) AS [EUR_Refund],
    SUM(CASE WHEN CM.OPCODE = 82 AND CM.VALCODE = 3 THEN CM.VSUM ELSE 0 END) AS [EUR_Pickup],
    SUM(CASE WHEN CM.OPCODE = 80 AND CM.VALCODE = 2 THEN CM.VSUM ELSE 0 END) AS [USD_Loan],       
    SUM(CASE WHEN CM.OPCODE = 72 AND CM.VALCODE = 2 THEN CM.VSUM ELSE 0 END) AS [USD_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 2 THEN CM.VSUM ELSE 0 END) AS [USD_Refund],
    SUM(CASE WHEN CM.OPCODE = 82 AND CM.VALCODE = 2 THEN CM.VSUM ELSE 0 END) AS [USD_Pickup],
    SUM(CASE WHEN CM.OPCODE = 80 AND CM.VALCODE = 1 THEN CM.VSUM ELSE 0 END) AS [KZT_Loan],
    SUM(CASE WHEN CM.OPCODE = 72 AND CM.VALCODE = 1 THEN CM.VSUM ELSE 0 END) AS [KZT_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 1 THEN CM.VSUM ELSE 0 END) AS [KZT_Refund],
    SUM(CASE WHEN CM.OPCODE = 82 AND CM.VALCODE = 1 THEN CM.VSUM ELSE 0 END) AS [KZT_Pickup],
    SUM(CASE WHEN CM.OPCODE = 80 AND CM.VALCODE = 5 THEN CM.VSUM ELSE 0 END) AS [RUB_Loan],
    SUM(CASE WHEN CM.OPCODE = 72 AND CM.VALCODE = 5 THEN CM.VSUM ELSE 0 END) AS [RUB_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 5 THEN CM.VSUM ELSE 0 END) AS [RUB_Refund],
    SUM(CASE WHEN CM.OPCODE = 82 AND CM.VALCODE = 5 THEN CM.VSUM ELSE 0 END) AS [RUB_Pickup],
    SUM(CASE WHEN CM.OPCODE = 80 AND CM.VALCODE = 4 THEN CM.VSUM ELSE 0 END) AS [CNY_Loan],
    SUM(CASE WHEN CM.OPCODE = 72 AND CM.VALCODE = 4 THEN CM.VSUM ELSE 0 END) AS [CNY_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 4 THEN CM.VSUM ELSE 0 END) AS [CNY_Refund],
    SUM(CASE WHEN CM.OPCODE = 82 AND CM.VALCODE = 4 THEN CM.VSUM ELSE 0 END) AS [CNY_Pickup],
    SUM(CASE WHEN CM.OPCODE = 70 AND CM.VALCODE = 10 THEN CM.VSUM ELSE 0 END) AS [Cards_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 10 THEN CM.VSUM ELSE 0 END) AS [Cards_Refund],
    SUM(CASE WHEN CM.OPCODE = 70 AND CM.VALCODE = 20 THEN CM.VSUM ELSE 0 END) AS [Offline_Sales],
    SUM(CASE WHEN CM.OPCODE = 74 AND CM.VALCODE = 20 THEN CM.VSUM ELSE 0 END) AS [Offline_Refund]    
FROM 
    silver.oper_cm_payments CM
LEFT JOIN bronze.ref_locations SL ON SL.STORECODE = LEFT(CM.CASHCODE, 3)
WHERE 
    CM.CASHCODE like ''28%'' --cast(date as date) = @Today
GROUP BY 
    SL.Location,
    SL.StoreName,
    CM.CASHCODE,
    CM.SHIFT,
    CAST(CM.DATE AS DATE),
    CASE 
        WHEN CAST(CM.TIME AS TIME) BETWEEN ''00:00:01'' AND ''08:00:00'' THEN N''Утро с 00:00:01 до 08:00:00''
        WHEN CAST(CM.TIME AS TIME) BETWEEN ''08:00:01'' AND ''20:00:00'' THEN N''День с 08:00:01 до 20:00:00''
        ELSE N''Вечер с 20:00:01 до 00:00:00''
        END
';
EXEC sp_executesql @sql;

END
GO



